version: '3'
services:
  back_app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  db:
    image: mongo
    container_name: db_mongo

  dbms:
    depends_on:
      - db
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db_mongo
