version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: db_mongo

  dbms:
    depends_on:
      - db
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db_mongo
